name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run extension
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: npm install
      - name: Install vscode extensions
        run: npm install -g @vscode/vsce
      - name: Package the extension
        run: vsce package
      - name: vsce publish
  # You may pin to the exact commit or the version.
  # uses: sigma/vsce-publish-action@b888dc8468ce39a3e940118f65f47a43ff1570cb
        uses: sigma/vsce-publish-action@v0.0.2
        with:
    # vsce token
          vsce_token: ${{ secrets.PA_TOKEN }}
