name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'
      - name: Run extension
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: npm install
      - name: Install vscode extensions
        run: npm install -g @vscode/vsce
      - name: Package the extension
        run: vsce package
      - name: Publish extension
        env:
          VSCE_PAT: ${{ secrets.PA_TOKEN }} 
        run: npx vsce publish --pat $VSCE_PAT
